### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by mthl** [oscaro/clj-gcloud-common#3]
Hello,

For the next release of the `clj-gcloud-common` we would have to choose a new version number. It would be nice to follow the convention of previous releases, however I don't understand the policy used by looking at previous version numbers.

@neuromantik33 and @bfontaine since you made the previous releases, I think you might provide some insights ?

**Comment by bfontaine** [comment]
Hello, see [`CONTRIBUTING.md`](https://github.com/oscaro/clj-gcloud-common/blob/master/CONTRIBUTING.md) 😉

**Comment by mthl** [comment]
Indeed, I overlooked that information.

Thanks for your answer @bfontaine.
